### ISSUE TITLE
Can't get Packet Event

### ISSUE THREAD

**Issue by laikee99** [mhsjlw/pocket-minecraft-protocol#160]
Hi, I am trying to use `on` to get events from server.
But now I get nothing, how can I get events?
Thanks.
```
client.on('event', (data,a)=>{
    console.log(data, a)  
})
```

**Comment by extremeheat** [comment]
what packet or event are you specifically trying to listen to?

the protocol docs are in https://minecraft-data.prismarine.js.org/?v=bedrock_1.18.0&d=protocol ; the emitted event names are the name of the packets in the ToC minus the "packet_" prefix

**Comment by laikee99** [comment]
And I used `useNativeRaknet: false`, but still got:
`You can suppress the error above by disabling useNativeRaknet in your options`.

```
const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  host: '127.0.0.1',   // optional
  port: 19132,         // optional, default 19132
  username: 'bot',   // the username you want to join as, optional if online mode
  offline: false,       // optional, default false. if true, do not login with Xbox Live. You will not be asked to sign-in if set to true.
  authTitle: "bot",
  useNativeRaknet: false
})

//console.log(client)

client.on('join', (a, clients) => {
    //console.log(a,clients)
    return 
})
client.on('event', (data,a)=>{
    console.log(data, a)    

    
})

client.on('simple_event', (data,a)=>{
            console.log(data, a)    

    
})


client.on('mob_effect', (data,a)=>{
            console.log(data, a)    
   
})

// The 'spawn' event is emitted. The chunks have been sent and all is well.
client.on('spawn', (clients) => {
    client.queue('text', {
      type: 'chat', needs_translation: false, source_name: client.username, xuid: '', platform_chat_id: '',
      message: "Respawned"//`${packet.source_name} said: ${packet.message} on ${new Date().toLocaleString()}`
    })
    console.log('Player has spawned!')
    
})

// We can listen for text packets. See proto.yml for documentation.
client.on('text', (packet) => {
  console.log('Client got text packet', packet)
})

```

**Comment by extremeheat** [comment]
raknet-native is required, the JS raknet implementation does not fully work at the moment, install it with `npm install raknet-native`

**Comment by laikee99** [comment]
> packet_

Hi, Thanks for reply, I want to get the `player death` event. But it's in the protocol event.
So isn't it should be `protocol_event` ?
And during the test, I found that the `client.on('text')` doesn't get the message.

**Comment by laikee99** [comment]
> npm install raknet-native

Thank you, I have install the `raknet-native`, and set it to be true, but still get  `You can suppress the error above by disabling useNativeRaknet in your options`.

The server is 1.18.1.

**Comment by laikee99** [comment]
```
 → /data/wwwroot/bot/node_modules/raknet-native/build/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/build/Debug/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/build/Release/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/out/Debug/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/Debug/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/out/Release/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/Release/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/build/default/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/compiled/16.13.0/linux/x64/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node
 → /data/wwwroot/bot/node_modules/raknet-native/lib/binding/node-v93-linux-x64/node-raknet.node
    at bindings (/data/wwwroot/bot/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/data/wwwroot/bot/node_modules/raknet-native/binding.js:29:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/wwwroot/bot/node_modules/raknet-native/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  tries: [
    '/data/wwwroot/bot/node_modules/raknet-native/build/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/build/Debug/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/build/Release/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/out/Debug/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/Debug/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/out/Release/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/Release/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/build/default/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/compiled/16.13.0/linux/x64/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node',
    '/data/wwwroot/bot/node_modules/raknet-native/lib/binding/node-v93-linux-x64/node-raknet.node'
  ]
}
```
node version: v16.13.0

**Comment by extremeheat** [comment]
join the discord for support questions - https://discord.gg/GsEFRM8 

I recommend clicking on the "Open in Gitpod" badge in the readme and trying through there to confirm a possible issue (open examples folder and alter the client script)

**Comment by laikee99** [comment]
> join the discord for support questions - https://discord.gg/GsEFRM8
> 
> I recommend clicking on the "Open in Gitpod" badge in the readme and trying through there to confirm a possible issue (open examples folder and alter the client script)

Thank you, I solved this problem, it's network issue.
