### ISSUE TITLE
HOW TO RUN IN REPLIT

### ISSUE THREAD

**Issue by GranGuorgeMC** [mhsjlw/pocket-minecraft-protocol#176]
![image](https://user-images.githubusercontent.com/90460977/152671723-4b068807-b1d8-443b-a779-5d0efb71f6d6.png)

**Here is the error**
```Unable to connect to [207.244.250.202:]/27783. Is the server running?
/home/runner/node-bot-mC/main/node_modules/bedrock-protocol/src/rak.js:57
    }, timeout, () => { throw new Error('Ping timed out') })
                              ^

Error: Ping timed out
    at /home/runner/node-bot-mC/main/node_modules/bedrock-protocol/src/rak.js:57:31
    at waitFor (/home/runner/node-bot-mC/main/node_modules/bedrock-protocol/src/datatypes/util.js:30:26)
    at async Client.ping (/home/runner/node-bot-mC/main/node_modules/bedrock-protocol/src/client.js:84:14)
exit status 1
 
```

**Here is the Code**
```const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  host: '207.244.250.202:',   // optional
  port: 27783,         // optional, default 19132
  username: 'Notch',   // the username you want to join as, optional if online mode
  offline: true       // optional, default false. if true, do not login with Xbox Live. You will not be asked to sign-in if set to true.
})

client.on('text', (packet) => { // Listen for chat messages and echo them back.
  if (packet.source_name != client.options.username) {
    client.queue('text', {
      type: 'chat', needs_translation: false, source_name: client.username, xuid: '', platform_chat_id: '',
      message: `${packet.source_name} said: ${packet.message} on ${new Date().toLocaleString()}`
    })
  }
})
```

**I dont know why it wont work in replit. but its works in my PC** 
they decame version "node version 16"

You can fix this?

**Comment by extremeheat** [comment]
Hostname is wrong

**Comment by extremeheat** [comment]
Closing as no other updates on the issue, reopen if you have more information

**Comment by GranGuorgeMC** [comment]
But the hostname is correct

I re edit it i remove the : 
And the error is not remove

And im sure that the ip and the port is correct

**Comment by extremeheat** [comment]
Does it work locally or on gitpod?

**Comment by GranGuorgeMC** [comment]
It work in my local in windows 

But in replit is not

**Comment by extremeheat** [comment]
Yes so it sounds like the port is blocked there. Try a different host.
