### ISSUE TITLE
Raknet fails to build during install

### ISSUE THREAD

**Issue by LucienHH** [mhsjlw/pocket-minecraft-protocol#201]
When installing bedrock-protocol on a Linux system running Ubuntu with an ARM based processor I get the following error:

I've installed CMake 3.16.3 and build-essential .

side note in case it's useful, I was able to install node-leveldb-zlib without any issues as I believe that has a pre-build step similar to this but no luck with bedrock-protocol / node-raknet

```
npm ERR! code 1
npm ERR! path /home/ubuntu/Test-App/node_modules/raknet-native
npm ERR! command failed
npm ERR! command sh -c node buildChecks.js
npm ERR! Error: Could not locate the bindings file. Tried:
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/build/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/build/Debug/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/build/Release/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/out/Debug/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/Debug/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/out/Release/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/Release/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/build/default/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/compiled/16.6.1/linux/arm64/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node
npm ERR!  → /home/ubuntu/Test-App/node_modules/raknet-native/lib/binding/node-v93-linux-arm64/node-raknet.node
npm ERR!     at bindings (/home/ubuntu/Test-App/node_modules/bindings/bindings.js:126:9)
npm ERR!     at Object.<anonymous> (/home/ubuntu/Test-App/node_modules/raknet-native/binding.js:30:33)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:94:18)
npm ERR!     at checkIfPrebuildExists (/home/ubuntu/Test-App/node_modules/raknet-native/buildChecks.js:7:22)
npm ERR!     at Object.<anonymous> (/home/ubuntu/Test-App/node_modules/raknet-native/buildChecks.js:20:7) {
npm ERR!   tries: [
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/build/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/build/Debug/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/build/Release/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/out/Debug/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/Debug/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/out/Release/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/Release/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/build/default/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/compiled/16.6.1/linux/arm64/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node',
npm ERR!     '/home/ubuntu/Test-App/node_modules/raknet-native/lib/binding/node-v93-linux-arm64/node-raknet.node'
npm ERR!   ]
npm ERR! }
npm ERR! [raknet] need to build
npm ERR! Build checks are passing! Building...
npm ERR! [
npm ERR!   '/home/ubuntu/.nvm/versions/node/v16.6.1/bin/node',
npm ERR!   '/home/ubuntu/Test-App/node_modules/.bin/cmake-js',
npm ERR!   'compile'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is GNU 9.4.0
npm ERR! -- The CXX compiler identification is GNU 9.4.0
npm ERR! -- Check for working C compiler: /usr/bin/cc
npm ERR! -- Check for working C compiler: /usr/bin/cc -- works
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Check for working CXX compiler: /usr/bin/c++
npm ERR! -- Check for working CXX compiler: /usr/bin/c++ -- works
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- NAPI DIR='/home/ubuntu/Test-App/node_modules/node-addon-api'
npm ERR! -- Include dirs
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/raknet-native/raknet/Source'
npm ERR! -- dir='/home/ubuntu/.cmake-js/node-arm64/v16.6.1/include/node'
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/nan'
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/node-addon-api'
npm ERR! -- Configuring done
npm ERR! -- Generating done
npm ERR! -- Build files have been written to: /home/ubuntu/Test-App/node_modules/raknet-native/build
npm ERR! Scanning dependencies of target RakNetLibStatic
npm ERR! [  0%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/Base64Encoder.cpp.o
npm ERR! [  1%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/BitStream.cpp.o
npm ERR! [  2%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CCRakNetSlidingWindow.cpp.o
npm ERR! [  3%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CCRakNetUDT.cpp.o
npm ERR! [  4%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CheckSum.cpp.o
npm ERR! [  5%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudClient.cpp.o
npm ERR! [  5%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudCommon.cpp.o
npm ERR! [  6%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudServer.cpp.o
npm ERR! [  7%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CommandParserInterface.cpp.o
npm ERR! [  8%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/ConnectionGraph2.cpp.o
npm ERR! [  9%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/ConsoleServer.cpp.o
npm ERR! [ 10%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DR_SHA1.cpp.o
npm ERR! [ 11%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_BytePool.cpp.o
npm ERR! [ 11%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_ByteQueue.cpp.o
npm ERR! [ 12%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_HuffmanEncodingTree.cpp.o
npm ERR! [ 13%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_Table.cpp.o
npm ERR! [ 14%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DataCompressor.cpp.o
npm ERR! [ 15%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DirectoryDeltaTransfer.cpp.o
npm ERR! [ 16%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DynDNS.cpp.o
npm ERR! [ 17%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/EmailSender.cpp.o
npm ERR! [ 17%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/EpochTimeToString.cpp.o
npm ERR! [ 18%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/FileList.cpp.o
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is GNU 9.4.0
npm ERR! -- The CXX compiler identification is GNU 9.4.0
npm ERR! -- Check for working C compiler: /usr/bin/cc
npm ERR! -- Check for working C compiler: /usr/bin/cc -- works
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Check for working CXX compiler: /usr/bin/c++
npm ERR! -- Check for working CXX compiler: /usr/bin/c++ -- works
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- NAPI DIR='/home/ubuntu/Test-App/node_modules/node-addon-api'
npm ERR! -- Include dirs
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/raknet-native/raknet/Source'
npm ERR! -- dir='/home/ubuntu/.cmake-js/node-arm64/v16.6.1/include/node'
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/nan'
npm ERR! -- dir='/home/ubuntu/Test-App/node_modules/node-addon-api'
npm ERR! -- Configuring done
npm ERR! -- Generating done
npm ERR! -- Build files have been written to: /home/ubuntu/Test-App/node_modules/raknet-native/build
npm ERR! Scanning dependencies of target RakNetLibStatic
npm ERR! [  0%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/Base64Encoder.cpp.o
npm ERR! [  1%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/BitStream.cpp.o
npm ERR! [  2%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CCRakNetSlidingWindow.cpp.o
npm ERR! [  3%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CCRakNetUDT.cpp.o
npm ERR! [  4%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CheckSum.cpp.o
npm ERR! [  5%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudClient.cpp.o
npm ERR! [  5%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudCommon.cpp.o
npm ERR! [  6%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CloudServer.cpp.o
npm ERR! [  7%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/CommandParserInterface.cpp.o
npm ERR! [  8%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/ConnectionGraph2.cpp.o
npm ERR! [  9%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/ConsoleServer.cpp.o
npm ERR! [ 10%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DR_SHA1.cpp.o
npm ERR! [ 11%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_BytePool.cpp.o
npm ERR! [ 11%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_ByteQueue.cpp.o
npm ERR! [ 12%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_HuffmanEncodingTree.cpp.o
npm ERR! [ 13%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DS_Table.cpp.o
npm ERR! [ 14%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DataCompressor.cpp.o
npm ERR! [ 15%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DirectoryDeltaTransfer.cpp.o
npm ERR! [ 16%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/DynDNS.cpp.o
npm ERR! [ 17%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/EmailSender.cpp.o
npm ERR! [ 17%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/EpochTimeToString.cpp.o
npm ERR! [ 18%] Building CXX object raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/FileList.cpp.o
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/home/ubuntu/Test-App/node_modules/raknet-native',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.3.0',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ubuntu/Test-App/node_modules/raknet-native/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/home/ubuntu/.cmake-js/node-arm64/v16.6.1/include/node;/home/ubuntu/Test-App/node_modules/nan',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=16.6.1',
npm ERR! info RUN   '-DNODE_ARCH=arm64'
npm ERR! info RUN ]
npm ERR! CMake Warning (dev) at CMakeLists.txt:7 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! CMake Warning (dev) at CMakeLists.txt:8 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! CMake Warning (dev) at CMakeLists.txt:9 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! info CMD BUILD
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '--build',
npm ERR! info RUN   '/home/ubuntu/Test-App/node_modules/raknet-native/build',
npm ERR! info RUN   '--config',
npm ERR! info RUN   'Release'
npm ERR! info RUN ]
npm ERR! /home/ubuntu/Test-App/node_modules/raknet-native/raknet/Source/FileList.cpp:24:10: fatal error: sys/io.h: No such file or directory
npm ERR!    24 | #include <sys/io.h>
npm ERR!       |          ^~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make[2]: *** [raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/build.make:336: raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/FileList.cpp.o] Error 1
npm ERR! make[1]: *** [CMakeFiles/Makefile2:159: raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/all] Error 2
npm ERR! make: *** [Makefile:130: all] Error 2
npm ERR! info REP Build has been failed, trying to do a full rebuild.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/home/ubuntu/Test-App/node_modules/raknet-native/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/home/ubuntu/Test-App/node_modules/raknet-native',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.3.0',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ubuntu/Test-App/node_modules/raknet-native/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/home/ubuntu/.cmake-js/node-arm64/v16.6.1/include/node;/home/ubuntu/Test-App/node_modules/nan',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=16.6.1',
npm ERR! info RUN   '-DNODE_ARCH=arm64'
npm ERR! info RUN ]
npm ERR! CMake Warning (dev) at CMakeLists.txt:7 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! CMake Warning (dev) at CMakeLists.txt:8 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! CMake Warning (dev) at CMakeLists.txt:9 (set):
npm ERR!   implicitly converting 'FALSE' to 'STRING' type.
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR!
npm ERR! info CMD BUILD
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '--build',
npm ERR! info RUN   '/home/ubuntu/Test-App/node_modules/raknet-native/build',
npm ERR! info RUN   '--config',
npm ERR! info RUN   'Release'
npm ERR! info RUN ]
npm ERR! /home/ubuntu/Test-App/node_modules/raknet-native/raknet/Source/FileList.cpp:24:10: fatal error: sys/io.h: No such file or directory
npm ERR!    24 | #include <sys/io.h>
npm ERR!       |          ^~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make[2]: *** [raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/build.make:336: raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/FileList.cpp.o] Error 1
npm ERR! make[1]: *** [CMakeFiles/Makefile2:159: raknet/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/all] Error 2
npm ERR! make: *** [Makefile:130: all] Error 2
npm ERR! ERR! OMG Process terminated: 2
npm ERR! node:child_process:826
npm ERR!     err = new Error(msg);
npm ERR!           ^
npm ERR!
npm ERR! Error: Command failed: cmake-js compile
npm ERR!     at checkExecSyncError (node:child_process:826:11)
npm ERR!     at Object.execSync (node:child_process:900:15)
npm ERR!     at /home/ubuntu/Test-App/node_modules/raknet-native/buildChecks.js:52:10
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [ null, null, null ],
npm ERR!   pid: 10017,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
```

**Comment by LucienHH** [comment]
Ah so the aarch64 build doesn't include sys/io.h at least that's what it seems? https://github.com/facebookarchive/RakNet/issues/146 Suggests commenting out the lines which use it as a workaround

**Comment by extremeheat** [comment]
Please open in dependency repo for node-raknet-native

**Comment by extremeheat** [comment]
Should be fixed with https://github.com/extremeheat/node-raknet-native/pull/17 v1.2.2
