### ISSUE TITLE
Client failed to read packet PartialReadError: Read error for undefined : Missing characters in string, found size is 450 expected size was 137445

### ISSUE THREAD

**Issue by MrWilco** [mhsjlw/pocket-minecraft-protocol#238]
When Attempting to join any Realm / World, this error is thrown.

```
Connecting to server Dedicated Server (undefined), version 1.19.10
While decoding 0c343edafcf3b094dd2a6237db0955c49f0957696c636f323933330c00c5b108c00000c2420f0ff741000000000000000000000000f84da64110e10643000000000401000000fe6c0a00000000000000000000024700078080c0808080c00101020202020003000004040957696c636f3239333305070106070007012c010802000900000a00001600001a00001b02041c0600000025070126030000803f2700002a012c012b02002c00002d02002e020035039a99193f36036666e63f38080000000000000000000000003900003a03000000003b00003c03000000004600004704004804004900014a00004b02004c02004d02004e02015100015200005404005807015b02005c07808080106404006502006602006702006802006a02066b00016c03000000416d03000080416e0407616d6269656e746f030000803f71000072020073020074020075020076050a000077000078050a00007903000000007d030000803f7e02287f02f406800106000000810102008201000001000000feffffff0201010100ffff0300ff0d0000cdcc4c3dcdcccc3d002462643432383030302d393161302d333934632d616565372d66663131663231666666616307000000
While decoding fe857028f3025cb089382c25ae16bbe6fc46ce4256626c2b7e487b3ed90f72b5ec90a930425ce220c5ecb7ce04061d8f7e08d76ba7c9cce0b402de4566c6f5b96daf4ebfaeca6d33a93e3f11b78fb63f21db267a214dcd44604b20afd5048f2d9a43397d9d6cac1bf77ed02f3179b5e62eb70d17c175687e0a104015b77d6159c06647e8b3b8543b35b018cebfffea97bd1d3b187b2767323aa1824be0fe193a55f7cc53750ae3cfa8d04539800f12b1ec46b0430e47f2b40422d4bed26ab29aecb72eaec1d6bc8a75c508c400477f6425f220e16a772154c42f53f378ba71ceb48d6942468c296646873a7d1520013155811d399f7879e89e249a8e6774b04508b8f90e56b1b36d3699b3ebd0f836311a1070259477e5dc5b85d3d920c8995a69e5fa6fb43955887223d79a7cc17bb89cfc11df9f0a9733870df3f86e0a1a47cc7c24668e3612eda9ceec55bdada0c0c1c4b03c749c8f9a7843118af12fcff6f088cf2e17a843394ed4cb40a7ecdc2e1b844dc70b1f4d92b352c68cabdba8be6f71cceb42d2e10fe9ede285df6fe8dc6096b2660394d32c140d708c638522724411af69bd9efe52f79c84e2ce6bce2c6776194b44cdd537a6d5855b7aafe391730a848dd9aed02ae9e8fde9b68c02ce4701c87c9e7b05d8ce72b66cd8dd2f0a7084df050fe8058ee0406c337401b28c148659d7e5b102a5d4551a7c3ff8df7d9d58b29c07f93de5ea5d0e1a97c56cae46447c2688d80e06366f4100bc5ef7df1d370bec6ad526dcb450523ee9fc62ab590db481d6daa59a21d929406ec903604344f6aebb3d8a0f3136bf79f954074df69ec8db76acb50787b6cb4a9d58fece7a5ba980532084895086ce7a7b1e155a22047b4aea146d85f837621f87df7f96aa0f2cc91129ba1b3aa95fc20210506cf9c1fed6dbd36dda7928270af2182bd40d2a1ab0c483fb52e2119317d0eecdc114a3e74e34d341ba938d633dc856c513a2
Client failed to read packet PartialReadError: Read error for undefined : Missing characters in string, found size is 450 expected size was 137445
    at new ExtendableError (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:258:12), <anonymous>:4250:15)
    at Object.packet_add_player (eval at compile (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1988:81)
    at eval (eval at compile (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1593:60)
    at mcpe_packet (eval at compile (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1769:9)
    at CompiledProtodef.read (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:70:12)
    at e.message (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:111:49)
    at tryCatch (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (C:\Users\Owner\Desktop\WilcoMCRealmBot\MCBot_Realms\node_modules\protodef\src\compiler.js:111:29) {
  partialReadError: true
}
```

npm version 7.20.0
node version 16.13.1
package version 3.15.0

**Comment by extremeheat** [comment]
Cannot reproduce any problems. When updating, you need to do `npm update`. If you use an older version of npm you will need to do `npm update --depth 9999` to update all the dependencies.

Deserializing with protodef and mcdata works correctly to give this output :

```js
{
  uuid: '343edafc-f3b0-94dd-2a62-37db0955c49f',
  username: 'Wilco2933',
  runtime_id: 12n,
  platform_chat_id: '',
  position: { x: -2.135850191116333, y: 97, z: 30.882352828979492 },
  velocity: { x: 0, y: 0, z: 0 },
  pitch: 20.788070678710938,
  yaw: 134.879150390625,
  head_yaw: 0,
  held_item: {
    network_id: 2,
    count: 1,
    metadata: 0,
    has_stack_id: 0,
    stack_id: undefined,
    block_runtime_id: 6975,
    extra: { has_nbt: 0, nbt: undefined, can_place_on: [], can_destroy: [] }
  },
  gamemode: 'creative',
  metadata: [
    { key: 'flags', type: 'long', value: [Object] },
    { key: 'health', type: 'int', value: 1 },
    { key: 'variant', type: 'int', value: 0 },
    { key: 'color', type: 'byte', value: 0 },
    { key: 'nametag', type: 'string', value: 'Wilco2933' },
    { key: 'owner_eid', type: 'long', value: -1n },
    { key: 'target_eid', type: 'long', value: 0n },
    { key: 'air', type: 'short', value: 300 },
    { key: 'potion_color', type: 'int', value: 0 },
    { key: 'potion_ambient', type: 'byte', value: 0 },
    { key: 'jump_duration', type: 'byte', value: 0 },
    { key: 'charge_amount', type: 'byte', value: 0 },
    { key: 'player_flags', type: 'byte', value: 0 },
    { key: 'player_index', type: 'int', value: 2 },
    { key: 'player_bed_position', type: 'vec3i', value: [Object] },
    { key: 'lead_holder_eid', type: 'long', value: -1n },
    { key: 'scale', type: 'float', value: 1 },
    { key: 'interactive_tag', type: 'byte', value: 0 },
    { key: 'max_airdata_max_air', type: 'short', value: 300 },
    { key: 'mark_variant', type: 'int', value: 0 },
    { key: 'container_type', type: 'byte', value: 0 },
    { key: 'container_base_size', type: 'int', value: 0 },
    {
      key: 'container_extra_slots_per_strength',
      type: 'int',
      value: 0
    },
    {
      key: 'boundingbox_width',
      type: 'float',
      value: 0.6000000238418579
    },
    {
      key: 'boundingbox_height',
      type: 'float',
      value: 1.7999999523162842
    },
    { key: 'rider_seat_position', type: 'vec3f', value: [Object] },
    { key: 'rider_rotation_locked', type: 'byte', value: 0 },
    { key: 'rider_max_rotation', type: 'float', value: 0 },
    { key: 'rider_min_rotation', type: 'byte', value: 0 },
    { key: 'rider_rotation_offset', type: 'float', value: 0 },
    { key: 'has_command_block', type: 'byte', value: 0 },
    { key: 'command_block_command', type: 'string', value: '' },
    { key: 'command_block_last_output', type: 'string', value: '' },
    { key: 'command_block_track_output', type: 'byte', value: 1 },
    { key: 'controlling_rider_seat_number', type: 'byte', value: 0 },
    { key: 'strength', type: 'int', value: 0 },
    { key: 'max_strength', type: 'int', value: 0 },
    { key: 'spell_casting_color', type: 'int', value: 0 },
    { key: 'limited_life', type: 'int', value: -1 },
    { key: 'always_show_nametag', type: 'byte', value: 1 },
    { key: 'color_2', type: 'byte', value: 0 },
    { key: 'score_tag', type: 'string', value: '' },
    { key: 'agent', type: 'long', value: -1n },
    { key: 'eating_counter', type: 'int', value: 0 },
    { key: 'flags_extended', type: 'long', value: [Object] },
    { key: 'interact_text', type: 'string', value: '' },
    { key: 'trade_tier', type: 'int', value: 0 },
    { key: 'max_trade_tier', type: 'int', value: 0 },
    { key: 'trade_experience', type: 'int', value: 0 },
    { key: 'skin_id', type: 'int', value: 0 },
    { key: 'command_block_tick_delay', type: 'int', value: 3 },
    {
      key: 'command_block_execute_on_first_tick',
      type: 'byte',
      value: 1
    },
    { key: 'ambient_sound_interval', type: 'float', value: 8 },
    { key: 'ambient_sound_interval_range', type: 'float', value: 16 },
    {
      key: 'ambient_sound_event_name',
      type: 'string',
      value: 'ambient'
    },
    { key: 'fall_damage_multiplier', type: 'float', value: 1 },
    { key: 'can_ride_target', type: 'byte', value: 0 },
    { key: 'low_tier_cured_discount', type: 'int', value: 0 },
    { key: 'high_tier_cured_discount', type: 'int', value: 0 },
    { key: 'nearby_cured_discount', type: 'int', value: 0 },
    { key: 'nearby_cured_discount_timestamp', type: 'int', value: 0 },
    { key: 'hitbox', type: 'compound', value: [Object] },
    { key: 'is_buoyant', type: 'byte', value: 0 },
    { key: 'base_runtime_id', type: 'compound', value: [Object] },
    { key: 'freezing_effect_strength', type: 'float', value: 0 },
    { key: 'movement_sound_distance_offset', type: 'float', value: 1 },
    { key: 'heartbeat_interval_ticks', type: 'int', value: 20 },
    { key: 'heartbeat_sound_event', type: 'int', value: 442 },
    { key: 128, type: 'vec3i', value: [Object] },
    { key: 129, type: 'int', value: 0 },
    { key: 130, type: 'byte', value: 0 }
  ],
  unique_id: -8589934591n,
  permission_level: 'operator',
  command_permission: 'operator',
  abilities: [
    {
      type: 'base',
      allowed: [Object],
      enabled: [Object],
      fly_speed: 0.05000000074505806,
      walk_speed: 0.10000000149011612
    }
  ],
  links: [],
  device_id: '...',
  device_os: 'Win10'
}
```

**Comment by zLupa** [comment]
@extremeheat I'm having the same error and I just installed the library

```
Client failed to read packet PartialReadError: Read error for undefined : Missing characters in string, found size is 448 expected size was 14466
```

I think it started after i teleported the bot to me, but not sure.
The only options that I changed in my bedrock server are the default member permission to operator and enable allowlist (whitelist).

Edit:
The error seems only to appear when I enter the server.
When the bot enters the server and stay for a little bit, I can join and immediately the error appear, but when I reconnect the bot again, the error disappear, but the error appears again when reconnecting.

**Comment by extremeheat** [comment]
@zLupa et al-

There was an earlier issue with the protocol data being out of date, the new release of node-minecraft-data should fix the issue.

Please use `npm update --depth 9999` to update all the dependencies, and make a _new_ issue (with all information, including stack trace) if you continue to have problems not related to this specific one. This issue #238 in specific relates to an extraneous field in `add_player` packet. It was fixed by https://github.com/PrismarineJS/minecraft-data/pull/594
