### ISSUE TITLE
Failed to bind server on [0.0.0.0]/19137

### ISSUE THREAD

**Issue by xxAROX** [mhsjlw/pocket-minecraft-protocol#247]
Using node version 18.3.0
Running on Linux VPS
Port 19137 is __unused__.

Unknown bind__() error -1; port 19137.
Unknown bind__() error -1; port 19137.
Unknown bind__() error -1; port 19137.
Failed to bind server on [0.0.0.0]/19137, is the port free?
RPC-Socket is listening on port 20058.
/home/xxarox/Cosmetic-X/Backend/node_modules/raknet-native/lib/RakNet.js:89
    return this.server.listen(packets => {

TypeError: Server failed to start
    at Server.listen (/home/xxarox/Cosmetic-X/Backend/node_modules/raknet-native/lib/RakNet.js:89:24)
    at RakNativeServer.listen (/home/xxarox/Cosmetic-X/Backend/node_modules/bedrock-protocol/src/rak.js:117:17)
    at Server.listen (/home/xxarox/Cosmetic-X/Backend/node_modules/bedrock-protocol/src/server.js:76:25)
    at VerifyServer.start (/home/xxarox/Cosmetic-X/Backend/src/classes/VerifyServer.js:45:16)

*if you need any of the code, tell me.*

**Comment by xxAROX** [comment]
While Server.listen

**Comment by extremeheat** [comment]
Dupe #120

**Comment by extremeheat** [comment]
If you get any exception, bind to another port. If it works on a different port the issue is on your machine and not bedrock-protocol. Any errors about "Unknown bind()" can be ignored per #120.
