### ISSUE TITLE
Can't connect to 1.19.21 server

### ISSUE THREAD

**Issue by charlie-moomoo** [mhsjlw/pocket-minecraft-protocol#271]
My server is at 1.19.22 (same protocol as 1.19.21), but I can't connect to my server using bedrock-protocol
It occurs following error:
```js
Connecting to server §l§d牛牛§r的§l§a草原§r §l§c生存§r (undefined), version 1.19.22  (as 1.19.21)
Supported versions {
  '1.18.30': 503,
  '1.18.11': 486,
  '1.18.0': 475,
  '1.17.40': 471,
  '1.17.30': 465,
  '1.17.10': 448,
  '1.17.0': 440,
  '1.16.220': 431,
  '1.16.210': 428,
  '1.16.201': 422
}
C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\options.js:30
    throw Error(`Unsupported version ${options.version}`)
          ^

Error: Unsupported version 1.19.21
    at Object.validateOptions (C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\options.js:30:11)
    at Client.validateOptions (C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\client.js:70:13)
    at Client.init (C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\client.js:38:10)
    at C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\createClient.js:23:16
Emitted 'error' event on Client instance at:
    at C:\Users\Charlie\Desktop\node_modules\bedrock-protocol\src\createClient.js:24:28

Node.js v18.5.0
```
And I checked the version number, I'm on the latest version.
```powershell
PS C:\Users\Charlie\Desktop> npm list bedrock-protocol
Desktop@ C:\Users\Charlie\Desktop
└── bedrock-protocol@3.18.0
```

**Comment by extremeheat** [comment]
You need to update your dependencies. 

npm update --depth 9999

(in newer versions of node.js, `npm update` is enough. However, as explained in the doc [here](https://docs.npmjs.com/cli/v6/commands/npm-update#description), on older versions like npm v6 the `--depth 9999` argument is needed to actually update everything and not just first level dependencies).

**Comment by charlie-moomoo** [comment]
Thanks, it worked!
