### ISSUE TITLE
connection.js - TypeError: Cannot read properties of undefined (reading 'createPacketBuffer')

### ISSUE THREAD

**Issue by DJStompZone** [mhsjlw/pocket-minecraft-protocol#291]
Getting the following error when I try to use client.queue to send a text packet.

```js
/home/dj/project/node_modules/bedrock-protocol/src/connection.js:82
    const packet = this.serializer.createPacketBuffer({ name, params })
                                   ^
TypeError: Cannot read properties of undefined (reading 'createPacketBuffer')
    at Client.queue (/home/dj/project/node_modules/bedrock-protocol/src/connection.js:82:36)
    at DiscBot.onBroadcast (/home/dj/project/index.js:239:21)
    at Client.<anonymous> (/home/dj/project/index.js:173:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Package version: bedrock-protocol 3.20.0
Node.JS version(s): 16.15.0, 18.10.0
OS: Ubuntu 20.04 w/ kernel Linux 5.15.0-48-generic x86_64

Other relevant info: Never had any problems in the past with this same version of the package, this started happening when I started trying to incorporate createClient into a class constructor. Not sure if that's directly related, but it seemed worth mentioning.

**Comment by extremeheat** [comment]
Please provide sample code that can reproduce this issue

**Comment by DJStompZone** [comment]
```js
const axios = require("axios");
const loc = require("./loc");
const { Client, Intents, MessageEmbed, MessageAttachment, } = require("discord.js");
const { realmName, realmId, accountEmail, verboseMessageEvents, attemptAutoConnect, token, channelId, discordClientId, guildId, botName, xToDMap, picMap, ownerDiscordID, REALMEMBED, JOINHOOK, BANHOOK, WEBHOOK, REALMNAME, BOTNAME, } = require("./config.json");
const bedrock = require('./bedrock-protocol')
const chalk = import('chalk');

const realmargs = process.argv[2]?.toString() ?? "";
let realmid = '13036820'
if ((typeof parseInt(realmargs) === 'number') && (realmargs.length > 6)) { realmid = realmargs }

function purple(txt) { return chalk.rgb(130, 20, 200).bold(txt) }
function orange(txt) { return chalk.rgb(255, 130, 0).bold(txt) }
function OPO(f, m, l) { console.log(orange(f) + " " + purple(m) + " " + orange(l)) }
function POP(f, m, l) { console.log(purple(f) + " " + orange(m) + " " + purple(l)) }

pktrgx = new RegExp(/(entity|map|block|tick|level_chunk|update|inventory|sound|update_attributes)/)
ignorepackets = ["event", "set_time", "level_event"]
logpaknames = pk = 1
function rtest(t) { return !!pktrgx.exec(t) }

function hasMentions(st) {
    const m = /<@[0-9]+>/.exec(st);
    if (m?.length) {
        return m[0];
    }
    return null;
}

function chkMsg(discordMessage) {
    let emojex = /<a?:[a-zA-Z0-9_]+:[0-9]+>/g;
    let matches = [...discordMessage.matchAll(emojex)];
    if (!matches?.length) {
        return discordMessage;
    }
    let msg = discordMessage;
    for (const i of Array(matches?.length ?? 0).keys()) {
        msg = msg.replace(matches[i][0], `(${matches[i][0].split(":")[1].toLowerCase()} emoji)`);
    }
    return msg;
}

function parseLocalText(itxt) {
    const inp = itxt.replaceAll("%", "").replaceAll(".", "_");
    if (inp.split(" ").length === 1 && Object.keys(loc.default).includes(inp)) {
        return loc.default[inp];
    }
    return inp
        .split(" ")
        .map((itm) => loc.default[itm] || itm)
        .join(" ");
}

function logOrIgnore(packetname) {
    try {
        if (logpaknames !== 1) { return }
        if (rtest(packetname) === true) { return }
        if (ignorepackets.includes(packetname)) { return }
        OPO("Recieved a", packetname, "packet.")
    } catch { }
}


class DiscBot {
    constructor() {
        this.stringToColor = function (str) {
            let hash = 0;
            for (var i = 0; i < str.length; i++) {
                hash = str.charCodeAt(i) + ((hash << 5) - hash);
            }
            let color = "#";
            for (var i = 0; i < 3; i++) {
                const value = (hash >> (i * 8)) & 0xff;
                color += ("00" + value.toString(16)).substr(-2);
            }
            return color;
        };
        this.fancyHash = function (str) {
            let h1 = 1779033703, h2 = 3144134277, h3 = 1013904242, h4 = 2773480762;
            for (let i = 0, k; i < str.length; i++) {
                k = str.charCodeAt(i);
                h1 = h2 ^ Math.imul(h1 ^ k, 597399067);
                h2 = h3 ^ Math.imul(h2 ^ k, 2869860233);
                h3 = h4 ^ Math.imul(h3 ^ k, 951274213);
                h4 = h1 ^ Math.imul(h4 ^ k, 2716044179);
            }
            h1 = Math.imul(h3 ^ (h1 >>> 18), 597399067);
            h2 = Math.imul(h4 ^ (h2 >>> 22), 2869860233);
            h3 = Math.imul(h1 ^ (h3 >>> 17), 951274213);
            h4 = Math.imul(h2 ^ (h4 >>> 19), 2716044179);
            return [
                (h1 ^ h2 ^ h3 ^ h4) >>> 0,
                (h2 ^ h1) >>> 0,
                (h3 ^ h1) >>> 0,
                (h4 ^ h1) >>> 0,
            ];
        };
        this.mcColor = function (str) {
            const colormap = {
                "0": "a",
                "1": "1",
                "2": "2",
                "3": "4",
                "4": "5",
                "5": "6",
                "6": "b",
                "7": "c",
                "8": "d"
            };
            const pick = this.fancyHash(str)[0].toString()[5];
            if (parseInt(pick) === 8) {
                return colormap["0"];
            }
            else if (parseInt(pick) === 9) {
                return colormap["7"];
            }
            else
                return colormap[pick];
        };
        this.discordClient = new Client({
            intents: [
                Intents.FLAGS.GUILDS,
                Intents.FLAGS.GUILD_MESSAGES,
                Intents.FLAGS.GUILD_MEMBERS,
            ],
        });
        this.getRealmClient = function () {
            const c = bedrock.createClient({ realms: { realmId: realmid } })
            c.on('text', (packet) => {
                try {
                    if ((packet.source_name != client.username) && (packet.type === "chat")) {
                        this.handle_realm_message(packet.source_name, packet.message)
                    }
                } catch { }
            })
            c.on('packet', (packet) => { logOrIgnore(packet.data.name) })
            return c
        }
        this.client = this.getRealmClient()
        this.handle_realm_message = function (source, message) {
            try {
                POP(source, "said:", message)
                this.onRealmMessage({ sender: source, message: message })
            } catch { }
        }
    }
    onStartup() {
        const client = this.client        

        const discordClient = this.discordClient;

        discordClient.login(token);

        discordClient.on("ready", async () => {
            const guild = await discordClient.guilds.fetch(guildId);
            console.info("RealmsCord: Phoenix - Discord discordClient Ready, setting activity...");
            discordClient.user.setActivity(`over ${realmName}`, { type: "WATCHING" });
            console.info("RealmsCord: Phoenix - Activity set.");
            console.info(`Now bridged with Discord as ${discordClient.user.username}`);
            const fancyStartMSG = new MessageEmbed()
                .setColor("#139dbf")
                .setTitle("Realmscord: Phoenix")
                .setDescription(`**${realmName}'s chat has been bridged with Discord**`)
                .setImage('https://i.imgur.com/FJ4yR0P.png');
            discordClient.channels.fetch(channelId).then(async (channel) => await channel
                .send({ embeds: [fancyStartMSG] })
                .then((msg) => {
                    setTimeout(() => msg.delete(), 300000);
                })
                .catch((error) => {
                    console.error(error);
                }));
            this.onBroadcast(`§a§l§oRealmscord has been connected.`);
        });

        discordClient.on("messageCreate", (message) => {
            this.onDiscordMessage(message);
        });
    }
    async onRealmMessage(packet) {
        try {
            const messageRanks = "";
            if (verboseMessageEvents && packet.sender) {
                console.info(`New realm message: [${packet.sender}]: "${packet.message}"`);
            }
            let playerMessage = "";
            if (packet.sender) {
                playerMessage += `<**${packet.sender}**> ${packet.message}`;
            }
            else {
                playerMessage += `<**${packet.message.substr(2)}**>`;
            }
            const fancyMSG = new MessageEmbed()
                .setColor(this.stringToColor(packet.sender))
                .setDescription(playerMessage);
            await discordClient.channels
                .fetch(channelId)
                .then(async (channel) => await channel.send({ embeds: [fancyMSG] }))
                .catch((error) => {
                    console.error(error);
                });
        } catch (er) { console.error(er.message) }
    }
    async onDiscordMessage(message) {
        if (message.author.id === discordClientId || message.content.length === 0 || message.channel.id !== channelId) {
            return;
        }
        let msg = message.content;
        const mentions = hasMentions(msg);
        const hasInvalid = !/^[\u0000-\u007f]*$/.test(msg);
        const msgAuthor = message?.author?.username ?? null;
        if (hasInvalid) {
            console.info(`Dropping message from [${msgAuthor}] with invalid characters`);
            return;
        }
        if (mentions) {
            const usrid = mentions.replace("<@", "").replace(">", "");
            const user = await this.discordClient.users.fetch(usrid);
            msg = message.content.replace(mentions, user.username);
        }
        if (verboseMessageEvents) {
            console.info(`New Discord message - [${msgAuthor}]: "${message.content}"`);
        }
        if (!msgAuthor) {
            await this.onBroadcast(`${msg}`);
            return;
        }
        else {
            await this.onBroadcast(`${msg}`, msgAuthor);
        }
    }
    async onBroadcast(messageEvent, msgAuthor) {
        let msg = `${chkMsg(messageEvent)}`;
        let nameColor;
        if (msgAuthor) {
            nameColor = `§${this.mcColor(msgAuthor)}` ?? "";
            msg = `§8[§9Discord§8]§f ${nameColor}${msgAuthor}§f§r: ${msg}`;
        }
        this.client.queue('text', {
            type: 'chat',
            needs_translation: false,
            source_name: this.client.username,
            xuid: '',
            platform_chat_id: '',
            message: msg
        })
    }
}


const bot = new DiscBot()
bot.onStartup()
```

**Comment by extremeheat** [comment]
You are not waiting for the client to join a server before trying to send a message to the server. See the client documentation for some special events to wait for if you're not responding to a server packet.
