### ISSUE TITLE
Checksum mismatch on server (1.19.50)

### ISSUE THREAD

**Issue by pappsamat** [mhsjlw/pocket-minecraft-protocol#334]
Based on code from [This example](https://github.com/PrismarineJS/bedrock-protocol/blob/master/examples/server/server.js), I am trying to spawn a client on my server. However, when I attempt to join the server (with a vanilla bedrock 1.19.50 client) the server either kicks the client and crashes with this error:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Checksum mismatch 15ddd3cb109c7b6b != e33601b8938309e0
    at Decipheriv.verify (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\transforms\encryption.js:68:28)
    at Decipheriv.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Decipheriv._transform (node:internal/crypto/cipher:154:8)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
Emitted 'error' event on Player instance at:
    at Decipheriv.verify (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\transforms\encryption.js:68:14)
    at Decipheriv.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at Writable.write (node:internal/streams/writable:337:10)

Node.js v18.12.1
```
Or the server continues to run, but still closes the connection, with this error:
```
minecraft-protocol while sending to ServerClient {
  address: '127.0.0.1/57318',
  guid: '13665664164908827110',
  send: [Function (anonymous)],
  close: [Function (anonymous)],
  neuter: [Function (anonymous)],
  sendReliable: [Function (anonymous)]
} Error: Failed to send: -5
    at Server.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:121:13)
    at ServerClient.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:63:35)
    at client.sendReliable (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\rak.js:102:21)
    at Player.sendMCPE (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:144:23)
    at Cipheriv.onEncryptedPacket (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:154:10)
    at Cipheriv.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Cipheriv._transform (node:internal/crypto/cipher:154:8) +97ms
  minecraft-protocol close connection 127.0.0.1/57318 undefined +2s
```
Both times, the client is kicked with the message: `could not deserialize tag.`:
![image](https://user-images.githubusercontent.com/86970314/210179024-cf4804d5-b34b-49aa-b40c-6cc1ab7af89f.png)
I am on Windows 11 (22H2), using node 18.12.1 and Minecraft 1.19.50.
Is there any way I can resolve this?

**Comment by CreeperG16** [comment]
Here is my code:
[index.txt](https://github.com/PrismarineJS/bedrock-protocol/files/10329126/index.txt)

**Comment by pappsamat** [comment]
Here is my code:
```js
process.env.DEBUG = process.argv.includes("--debug") ? "minecraft-protocol" : "";

const { Server } = require("bedrock-protocol");
const { readdir, readFile } = require("fs/promises");
const { WorldProvider } = require("bedrock-provider");
const { LevelDB } = require("leveldb-zlib");
const path = require("path");

const loadWorld = async () => {
    const filePath = path.join(__dirname, "world/Bedrock level/db");
    const db = new LevelDB(filePath, { createIfMissing: false });
    await db.open();
    const world = new WorldProvider(db, { dimension: 0 });

    const requestChunks = async (x, z, radius) => {
        const chunks = [];
        const cxStart = (x >> 4) - radius;
        const cxEnd = (x >> 4) + radius;
        const czStart = (z >> 4) - radius;
        const czEnd = (z >> 4) + radius;

        for (let cx = cxStart; cx < cxEnd; cx++) {
            for (let cz = czStart; cz < czEnd; cz++) {
                const chunkColumn = await world.load(cx, cz, true);
                if (!chunkColumn) continue;
                const chunkBuffer = await chunkColumn.networkEncodeNoCache();
                chunks.push({
                    x: cx,
                    z: cz,
                    sub_chunk_count: chunkColumn.sectionsLen,
                    cache_enabled: false,
                    blobs: [],
                    payload: chunkBuffer,
                });
            }
        }

        return chunks;
    };

    return { requestChunks };
};

const server = new Server({
    host: "127.0.0.1",
    port: 19130,
    version: "1.19.50",
    offline: process.argv.includes("--offline"),
});

server.on("connect", (client) => {
    const respawnPacket = {
        position: { x: 0, y: 0, z: 0 },
        state: 1,
        runtime_entity_id: 999n,
    };

    const item = {
        network_id: 0,
        count: 0,
        metadata: 0,
        has_stack_id: undefined,
        stack_id: undefined,
        extra: {
            has_nbt: false,
            nbt: { version: 1, nbt: undefined },
            can_place_on: [],
            can_destroy: [],
            blocking_tick: 0,
        },
    };

    const startGame = {
        entity_id: 999n,
        runtime_entity_id: 999n,
        player_gamemode: "fallback",
        player_position: { ...respawnPacket.position },
        rotation: { x: 0, z: 0 },
        seed: [0],
        biome_type: 0,
        biome_name: "plains",
        dimension: "overworld",
        generator: 1, // Maybe change this to flat?
        world_gamemode: "creative",
        difficulty: 0, // peaceful
        spawn_position: { ...respawnPacket.position },
        achievements_disabled: true,
        editor_world: false,
        day_cycle_stop_time: 19,
        edu_offer: 0,
        edu_features_enabled: false,
        edu_product_uuid: "",
        rain_level: 0,
        lightning_level: 0,
        has_confirmed_platfrom_locked_content: false,
        is_multiplayer: true, // lol
        broadcast_to_lan: true,
        xbox_live_broadcast_mode: 6,
        platform_broadcast_mode: 6,
        enable_commands: true,
        is_texturepacks_required: false,
        gamerules: [], // Should be OK? I send none in update pack too
        experiments: [],
        experiments_previously_used: false,
        bonus_chest: false,
        map_enabled: false,
        permission_level: 4,
        server_chunk_tick_range: 4,
        has_locked_behavior_pack: false,
        has_locked_resource_pack: false,
        is_from_locked_world_template: false,
        msa_gamertags_only: true,
        is_from_world_template: false,
        is_world_template_option_locked: false,
        only_spawn_v1_villagers: false,
        persona_disabled: false,
        custom_skins_disabled: false,
        game_version: "*",
        limited_world_width: 16,
        limited_world_length: 16,
        is_new_nether: false,
        edu_resource_uri: { button_name: "", link_uri: "" },
        experimental_gameplay_override: false,
        chat_restriction_level: "none",
        disable_player_interactions: false,
        level_id: "Test world",
        world_name: "Test world",
        premium_world_template_id: "00000000-0000-0000-0000-000000000000",
        is_trial: false,
        movement_authority: "server",
        rewind_history_size: 20,
        server_authoritative_block_breaking: false,
        current_tick: [0, 19],
        enchantment_seed: 2015466119,
        block_properties: [],
        itemstates: [],
        multiplayer_correlation_id: "3510d8ba-4215-4b6a-a8e7-8a0b64c34730",
        server_authoritative_inventory: true,
        engine: "1.19.50",
        property_data: { type: "compound", name: "", value: {} },
        block_pallette_checksum: [2449166282, 1110860179],
        world_template_id: "00000000-0000-0000-0000-000000000000",
        client_side_generation: true,
    };

    client.on("join", () => {
        console.log("Client joined:", client.getUserData());

        client.write("resource_packs_info", {
            must_accept: false,
            has_scripts: false,
            behaviour_packs: [],
            texture_packs: [],
        });

        client.write("resource_pack_stack", {
            must_accept: false,
            behavior_packs: [],
            resource_packs: [],
            game_version: "",
            experiments: [],
            experiments_previously_used: false,
        });

        client.once("resource_pack_client_response", async () => {
            console.log("RP Client response...");

            client.write("network_settings", { compression_threshold: 1 });

            for (let i = 0; i < 3; i++)
                client.queue("inventory_slot", { window_id: 120, slot: 0, item: { network_id: 0 } });

            client.queue("player_list", { records: { type: "add", records_count: 0, records: [], verified: true } });
            client.queue("start_game", startGame);
            client.queue("item_component", { entries: [] });

            client.queue("set_spawn_position", {
                spawn_type: "player",
                player_position: { x: 0, y: 0, z: 0 },
                dimension: 0,
                world_position: { x: 0, y: 0, z: 0 },
            });

            client.queue("set_time", { time: 0 });
            client.queue("set_difficulty", { difficulty: 1 });
            client.queue("set_commands_enabled", { enabled: true });

            client.queue("update_adventure_settings", {
                no_pvm: false,
                no_mvp: false,
                immutable_world: false,
                show_name_tags: true,
                auto_jump: false,
            });

            client.queue("biome_definition_list", { nbt: { type: "compound", name: "", value: {} } });

            client.queue("avaliable_entity_identifiers", {
                nbt: {
                    type: "compound",
                    name: "",
                    value: { idlist: { type: "list", value: { type: "compound", value: [] } } },
                },
            });

            client.queue("feature_registry", { features: [] });

            client.queue("update_attributes", { runtime_entity_id: 999n, attributes: [], tick: 0n });
            client.queue("creative_content", { items: [] });
            client.queue("inventory_content", { window_id: "inventory", input: new Array(36).fill({ network_id: 0 }) });
            client.queue("inventory_content", { window_id: "armor", input: new Array(4).fill({ network_id: 0 }) });
            client.queue("inventory_content", { window_id: "offhand", input: [{ network_id: 0 }] });
            client.queue("player_hotbar", { selected_slot: 4, window_id: "inventory", select_slot: true });

            client.queue("crafting_data", {
                recipes: [],
                potion_type_recipes: [],
                potion_container_recipes: [],
                material_reducers: [],
                clear_recipes: true,
            });

            client.queue("available_commands", {
                values_len: 0,
                _enum_type: "short",
                enum_values: [],
                suffixes: [],
                enums: [],
                command_data: [],
                dynamic_enums: [],
                enum_constraints: [],
            });

            client.queue("chunk_radius_update", { chunk_radius: 1 });
            client.queue("game_rules_changed", { rules: [] });
            client.queue("respawn", respawnPacket);

            let loop = setInterval(
                () =>
                    client.write("network_chunk_publisher_update", {
                        coordinates: { x: respawnPacket.position.x, y: 130, z: respawnPacket.position.z },
                        radius: 64,
                        saved_chunks: [],
                    }),
                50
            );

            // TODO: chunks
            console.log("Requesting chunks...");
            const { requestChunks } = await loadWorld();
            const chunks = await requestChunks(respawnPacket.position.x, respawnPacket.position.z, 2);
            console.log("Sending chunks...");
            for (const chunk of chunks) console.log("Sending chunk", chunk) || client.queue("level_chunk", chunk);
            console.log("Sent chunks.");

            // // const files = aáűűűűűűu77zőú - courtesy of Jellie the cat
            // ozőaaaaaaaaaaaaaqdssssssssssssssssssssssssssssssssqwwait readdir("./packets/chunks");
            // // for (const file of files) {
            // //     const buffer = await readFile(`./packets/chunks/${file}`);
            // //     console.log("Sending chunk...", buffer);
            // //     client.sendBuffer(buffer);
            // // }

            // client.write("network_chunk_publisher_update", {
            //     coordinates: { x: respawnPacket.position.x, y: 130, z: respawnPacket.position.z },
            //     radius: 64,
            //     saved_chunks: [],
            // });

            client.queue("set_health", { health: 20 });

            // wait for client to load chunks
            setTimeout(() => {
                client.write("play_status", { status: "player_spawn" });
            }, 6000);

            client.on("tick_sync", (packet) => {
                client.queue("tick_sync", {
                    request_time: packet.request_time,
                    response_time: BigInt(Date.now()),
                });
            });
        });
    });
});

server.listen();
console.log("Server listening on port %d.", server.options.port);
```

**Comment by pappsamat** [comment]
Logs:
```
PS C:\Users\tamaspapp\Documents\replay-server> node .\index.js --debug
Server listening on port 19130.
  minecraft-protocol Listening on 127.0.0.1 19130 1.19.50 +0ms
  minecraft-protocol new connection 127.0.0.1/59306 +15s
  minecraft-protocol * new status 2 +0ms
  minecraft-protocol S -> request_network_settings {"client_protocol":560} +0ms
  minecraft-protocol S <- network_settings {
  compression_threshold: 512,
  compression_algorithm: 'deflate',
  client_throttle: false,
  client_throttle_threshold: 0,
  client_throttle_scalar: 0
} +1ms
  minecraft-protocol S -> login {"protocol_version":560,"tokens":{"identity":"{\"chain\":[\"eyJ... +218ms
  minecraft-protocol Verified client with mojang key MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8ELkixyLcwlZryUQcu1TvPOmI2B7vX83ndnWRUaXm74wFfa5f/lwQNTfrLVHa2PmenpGI6JhIMUJaWZrjmMj90NoKNFSNBuKdm8rYiXsfaz3K36x/1U26HpG0ZxK/V1V +0ms
  minecraft-protocol [encrypt] Client pub key base64:  {
  key: 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEz9+yvC8biFBygNcLv+i8tAIviFKT6EQPNgU9Iq7C/6Q16VFKagKx08c1V0MNfMhNrchYdBA5P4u4PlCcm+JXJgo3bO85szLQM1n/AlPToyv/3OzcNAG2rXDofbDU3uL1'
} +0ms
  minecraft-protocol S <- server_to_client_handshake {
  token: 'eyJ...'
} +39ms
  minecraft-protocol S -> Started encryption <Buffer c6 28 78 7a 36 2f ce db 39 ed 7f e6 e4 2a b6 25 14 16 0a cc 9e 5b 0c cc f8 11 1a b2 cf 4a f3 b5 d2 ea e5 5c 1b 52 60 27 82 a8 42 d1 84 7f 01 97> <Buffer c8 95 28 93 55 1c 27 87 6a 08 d4 4f 20 e5 26 eb> +6ms
  minecraft-protocol S -> client_to_server_handshake {} +78ms
  minecraft-protocol S <- play_status { status: 'login_success' } +0ms
  minecraft-protocol * new status 3 +356ms
Client joined: {
  XUID: '2535423617062315',
  identity: '681825f5-bfd2-31fd-afff-691b3fffb713',
  displayName: 'CreeperG16',
  titleId: '896928775'
}
  minecraft-protocol S <- resource_packs_info {
  must_accept: false,
  has_scripts: false,
  behaviour_packs: [],
  texture_packs: []
} +6ms
  minecraft-protocol S <- resource_pack_stack {
  must_accept: false,
  behavior_packs: [],
  resource_packs: [],
  game_version: '',
  experiments: [],
  experiments_previously_used: false
} +2ms
  minecraft-protocol S -> client_cache_status {"enabled":true} +177ms
  minecraft-protocol S -> resource_pack_client_response {"response_status":"completed","resourcepackids":[]} +4ms
RP Client response...
  minecraft-protocol S <- network_settings { compression_threshold: 1 } +2ms
  minecraft-protocol S <- Q <-  inventory_slot { window_id: 120, slot: 0, item: { network_id: 0 } } +2ms
  minecraft-protocol S <- Q <-  inventory_slot { window_id: 120, slot: 0, item: { network_id: 0 } } +3ms
  minecraft-protocol S <- Q <-  inventory_slot { window_id: 120, slot: 0, item: { network_id: 0 } } +1ms
  minecraft-protocol S <- Q <-  player_list {
  records: { type: 'add', records_count: 0, records: [], verified: true }
} +1ms
  minecraft-protocol S <- Q <-  start_game {
  entity_id: 999n,
  runtime_entity_id: 999n,
  player_gamemode: 'fallback',
  player_position: { x: 0, y: 0, z: 0 },
  rotation: { x: 0, z: 0 },
  seed: [ 0 ],
  biome_type: 0,
  biome_name: 'plains',
  dimension: 'overworld',
  generator: 1,
  world_gamemode: 'creative',
  difficulty: 0,
  spawn_position: { x: 0, y: 0, z: 0 },
  achievements_disabled: true,
  editor_world: false,
  day_cycle_stop_time: 19,
  edu_offer: 0,
  edu_features_enabled: false,
  edu_product_uuid: '',
  rain_level: 0,
  lightning_level: 0,
  has_confirmed_platfrom_locked_content: false,
  is_multiplayer: true,
  broadcast_to_lan: true,
  xbox_live_broadcast_mode: 6,
  platform_broadcast_mode: 6,
  enable_commands: true,
  is_texturepacks_required: false,
  gamerules: [],
  experiments: [],
  experiments_previously_used: false,
  bonus_chest: false,
  map_enabled: false,
  permission_level: 4,
  server_chunk_tick_range: 4,
  has_locked_behavior_pack: false,
  has_locked_resource_pack: false,
  is_from_locked_world_template: false,
  msa_gamertags_only: true,
  is_from_world_template: false,
  is_world_template_option_locked: false,
  only_spawn_v1_villagers: false,
  persona_disabled: false,
  custom_skins_disabled: false,
  game_version: '*',
  limited_world_width: 16,
  limited_world_length: 16,
  is_new_nether: false,
  edu_resource_uri: { button_name: '', link_uri: '' },
  experimental_gameplay_override: false,
  chat_restriction_level: 'none',
  disable_player_interactions: false,
  level_id: 'Test world',
  world_name: 'Test world',
  premium_world_template_id: '00000000-0000-0000-0000-000000000000',
  is_trial: false,
  movement_authority: 'server',
  rewind_history_size: 20,
  server_authoritative_block_breaking: false,
  current_tick: [ 0, 19 ],
  enchantment_seed: 2015466119,
  block_properties: [],
  itemstates: [],
  multiplayer_correlation_id: '3510d8ba-4215-4b6a-a8e7-8a0b64c34730',
  server_authoritative_inventory: true,
  engine: '1.19.50',
  property_data: { type: 'compound', name: '', value: {} },
  block_pallette_checksum: [ 2449166282, 1110860179 ],
  world_template_id: '00000000-0000-0000-0000-000000000000',
  client_side_generation: true
} +3ms
  minecraft-protocol S <- Q <-  item_component { entries: [] } +38ms
  minecraft-protocol S <- Q <-  set_spawn_position {
  spawn_type: 'player',
  player_position: { x: 0, y: 0, z: 0 },
  dimension: 0,
  world_position: { x: 0, y: 0, z: 0 }
} +3ms
  minecraft-protocol S <- Q <-  set_time { time: 0 } +6ms
  minecraft-protocol S <- Q <-  set_difficulty { difficulty: 1 } +1ms
  minecraft-protocol S <- Q <-  set_commands_enabled { enabled: true } +22ms
  minecraft-protocol S <- Q <-  update_adventure_settings {
  no_pvm: false,
  no_mvp: false,
  immutable_world: false,
  show_name_tags: true,
  auto_jump: false
} +1ms
  minecraft-protocol S <- Q <-  biome_definition_list { nbt: { type: 'compound', name: '', value: {} } } +5ms
  minecraft-protocol S <- Q <-  avaliable_entity_identifiers { nbt: { type: 'compound', name: '', value: { idlist: [Object] } } } +1ms
  minecraft-protocol S <- Q <-  feature_registry { features: [] } +1ms
  minecraft-protocol S <- Q <-  update_attributes { runtime_entity_id: 999n, attributes: [], tick: 0n } +1ms
  minecraft-protocol S <- Q <-  creative_content { items: [] } +5ms
  minecraft-protocol S <- Q <-  inventory_content {
  window_id: 'inventory',
  input: [
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 },
    { network_id: 0 }, { network_id: 0 }
  ]
} +2ms
  minecraft-protocol S <- Q <-  inventory_content {
  window_id: 'armor',
  input: [
    { network_id: 0 },
    { network_id: 0 },
    { network_id: 0 },
    { network_id: 0 }
  ]
} +25ms
  minecraft-protocol S <- Q <-  inventory_content { window_id: 'offhand', input: [ { network_id: 0 } ] } +2ms
  minecraft-protocol S <- Q <-  player_hotbar { selected_slot: 4, window_id: 'inventory', select_slot: true } +4ms
  minecraft-protocol S <- Q <-  crafting_data {
  recipes: [],
  potion_type_recipes: [],
  potion_container_recipes: [],
  material_reducers: [],
  clear_recipes: true
} +48ms
  minecraft-protocol S <- Q <-  available_commands {
  values_len: 0,
  _enum_type: 'short',
  enum_values: [],
  suffixes: [],
  enums: [],
  command_data: [],
  dynamic_enums: [],
  enum_constraints: []
} +15ms
  minecraft-protocol S <- Q <-  chunk_radius_update { chunk_radius: 1 } +60ms
  minecraft-protocol S <- Q <-  game_rules_changed { rules: [] } +25ms
  minecraft-protocol S <- Q <-  respawn { position: { x: 0, y: 0, z: 0 }, state: 1, runtime_entity_id: 999n } +10ms
Requesting chunks...
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +125ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +129ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +60ms
  minecraft-protocol S -> resource_pack_client_response {"response_status":"have_all_packs","resourcepackids":[]} +24ms
  minecraft-protocol S -> login {"protocol_version":560,"tokens":{"identity":"{\"chain\":[\"eyJ... +22ms
  minecraft-protocol Verified client with mojang key MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8ELkixyLcwlZryUQcu1TvPOmI2B7vX83ndnWRUaXm74wFfa5f/lwQNTfrLVHa2PmenpGI6JhIMUJaWZrjmMj90NoKNFSNBuKdm8rYiXsfaz3K36x/1U26HpG0ZxK/V1V +977ms
  minecraft-protocol [encrypt] Client pub key base64:  {
  key: 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEz9+yvC8biFBygNcLv+i8tAIviFKT6EQPNgU9Iq7C/6Q16VFKagKx08c1V0MNfMhNrchYdBA5P4u4PlCcm+JXJgo3bO85szLQM1n/AlPToyv/3OzcNAG2rXDofbDU3uL1'
} +1s
  minecraft-protocol S <- server_to_client_handshake {
  token: 'eyJ...'
} +134ms
  minecraft-protocol S -> Started encryption <Buffer c6 28 78 7a 36 2f ce db 39 ed 7f e6 e4 2a b6 25 14 16 0a cc 9e 5b 0c cc f8 11 1a b2 cf 4a f3 b5 d2 ea e5 5c 1b 52 60 27 82 a8 42 d1 84 7f 01 97> <Buffer c8 95 28 93 55 1c 27 87 6a 08 d4 4f 20 e5 26 eb> +12ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +18ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +55ms
Sending chunks...
Sent chunks.
  minecraft-protocol S <- Q <-  set_health { health: 20 } +23ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +36ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +57ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +65ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +75ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +98ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +67ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +62ms
  minecraft-protocol S <- network_chunk_publisher_update { coordinates: { x: 0, y: 130, z: 0 }, radius: 64, saved_chunks: [] } +52ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Checksum mismatch 288aa28f3ea85665 != 755ee0977124c220
    at Decipheriv.verify (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\transforms\encryption.js:68:28)
    at Decipheriv.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Decipheriv._transform (node:internal/crypto/cipher:154:8)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
Emitted 'error' event on Player instance at:
    at Decipheriv.verify (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\transforms\encryption.js:68:14)
    at Decipheriv.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at Writable.write (node:internal/streams/writable:337:10)

Node.js v18.12.1
PS C:\Users\tamaspapp\Documents\replay-server> 
```

**Comment by extremeheat** [comment]
Does this happen with 1.19.1 or 1.19.40?

**Comment by pappsamat** [comment]
Tested on 1.19.40, same error, though the second one (failed to send -5) seems to happen more frequently

_Note: My version switcher doesn't have a version 1.19.1 listed but according to [the wiki](https://minecraft.fandom.com/wiki/Bedrock_Edition_1.19.0) Bedrock 1.19.0 is server version 1.19.1 so I tested with client v1.19.0.5_
On 1.19.1 however I am kicked with this message:
![image](https://user-images.githubusercontent.com/86970314/210397642-cf02880b-a5f3-4be2-88ef-b6941046429a.png)

And I get two "failed to send" errors:
```
minecraft-protocol while sending to ServerClient {
  address: '127.0.0.1/64204',
  guid: '10897906800474313725',
  send: [Function (anonymous)],
  close: [Function (anonymous)],
  neuter: [Function (anonymous)],
  sendReliable: [Function (anonymous)]
} Error: Failed to send: -3
    at Server.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:121:13)
    at ServerClient.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:63:35)
    at client.sendReliable (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\rak.js:102:21)
    at Player.sendMCPE (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:144:23)
    at Cipheriv.onEncryptedPacket (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:154:10)
    at Cipheriv.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Cipheriv._transform (node:internal/crypto/cipher:154:8) +4s
  minecraft-protocol while sending to ServerClient {
  address: '127.0.0.1/64204',
  guid: '10897906800474313725',
  send: [Function (anonymous)],
  close: [Function (anonymous)],
  neuter: [Function (anonymous)],
  sendReliable: [Function (anonymous)]
} Error: Failed to send: -3
    at Server.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:121:13)
    at ServerClient.send (C:\Users\tamaspapp\Documents\replay-server\node_modules\raknet-native\lib\RakNet.js:63:35)
    at client.sendReliable (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\rak.js:102:21)
    at Player.sendMCPE (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:144:23)
    at Cipheriv.onEncryptedPacket (C:\Users\tamaspapp\Documents\replay-server\node_modules\bedrock-protocol\src\connection.js:154:10)
    at Cipheriv.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Cipheriv._transform (node:internal/crypto/cipher:154:8) +5ms
  minecraft-protocol close connection 127.0.0.1/64204 undefined +4s
  minecraft-protocol S -> Client closed connection 127.0.0.1/64204 +50ms
```
As I know [bedrock-provider](https://github.com/PrismarineJS/bedrock-provider/blob/master/src/versions.ts#L33) doesn't support versions above 1.18 (unless there haven't been changes since then, which I doubt) I tried it with dumped chunk packets from a BDS of the same version, but I got the same result.

**Comment by extremeheat** [comment]
I'm not convinced this is a problem in bedrock-protocol. If you think so, please provide an example with the minimal amount of standalone code (max ~150 lines of code) that can reproduce the error.

**Comment by extremeheat** [comment]
Please reopen if you have more information
