### ISSUE TITLE
[  ERROR ] raknet-native

### ISSUE THREAD

**Issue by ThisMe124** [mhsjlw/pocket-minecraft-protocol#337]
I installed before and it was normal, but after I reinstalled with the new version I got an error like this, even though before it worked fine, without any errors.

```
Error: Command failed: npm i bedrock-protocol
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hawk@0.10.2',
npm WARN EBADENGINE   required: { node: '0.8.x' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.3.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hoek@0.7.6',
npm WARN EBADENGINE   required: { node: '0.8.x' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.3.0' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /home/container/node_modules/raknet-native
npm ERR! command failed
npm ERR! command sh -c node buildChecks.js
npm ERR! Error: Could not locate the bindings file. Tried:
npm ERR!  → /home/container/node_modules/raknet-native/build/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/build/Debug/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/build/Release/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/out/Debug/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/Debug/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/out/Release/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/Release/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/build/default/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/compiled/16.19.0/linux/x64/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node
npm ERR!  → /home/container/node_modules/raknet-native/lib/binding/node-v93-linux-x64/node-raknet.node
npm ERR!     at bindings (/home/container/node_modules/bindings/bindings.js:126:9)
npm ERR!     at Object.<anonymous> (/home/container/node_modules/raknet-native/binding.js:30:33)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1067:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at checkIfPrebuildExists (/home/container/node_modules/raknet-native/buildChecks.js:7:22)
npm ERR!     at Object.<anonymous> (/home/container/node_modules/raknet-native/buildChecks.js:20:7) {
npm ERR!   tries: [
npm ERR!     '/home/container/node_modules/raknet-native/build/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/build/Debug/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/build/Release/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/out/Debug/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/Debug/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/out/Release/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/Release/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/build/default/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/compiled/16.19.0/linux/x64/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node',
npm ERR!     '/home/container/node_modules/raknet-native/lib/binding/node-v93-linux-x64/node-raknet.node'
npm ERR!   ]
npm ERR! }
npm ERR! [raknet] need to build
npm ERR! Build checks are passing! Building...
npm ERR! [
npm ERR!   '/home/container/node_modules/node/bin/node',
npm ERR!   '/home/container/node_modules/.bin/cmake-js',
npm ERR!   'compile'
npm ERR! ]
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info DIST Downloading distribution files to: /home/container/.cmake-js/node-x64/v16.19.0
npm ERR! http DIST 	- https://nodejs.org/dist/v16.19.0/SHASUMS256.txt
npm ERR! http DIST 	- https://nodejs.org/dist/v16.19.0/node-v16.19.0-headers.tar.gz
npm ERR! info REP Build has been failed, trying to do a full rebuild.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: cmake-js compile
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execSync (node:child_process:932:15)
npm ERR!     at /home/container/node_modules/raknet-native/buildChecks.js:52:10
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [ null, null, null ],
npm ERR!   pid: 58,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2023-01-19T11_31_01_361Z-debug-0.log
```

**Comment by extremeheat** [comment]
As per the error, your computer is missing cmake which must be installed and available in the path. Without cmake build tools installed raknet-native cannot be compiled. 

Alternatively you can look at using the raknet-node raknet backend, as explained in the docs.

**Comment by ThisMe124** [comment]
> As per the error, your computer is missing cmake which must be installed and available in the path. Without cmake build tools installed raknet-native cannot be compiled.
> 
> Alternatively you can look at using the raknet-node raknet backend, as explained in the docs.

but I use hosting like hosting on pterodactly, is there a way to do it?

**Comment by extremeheat** [comment]
I can't comment on your specific situation, but here is a link to installing cmake on Linux systems, required for the default raknet-native backend:

https://robots.uc3m.es/installation-guides/install-cmake.html

You can get it with your systems package manager. Alternatively per our docs you can use raknet-node backend (explained in docs) which should have prebuilds for Linux.

**Comment by ThisMe124** [comment]
> I can't comment on your specific situation, but here is a link to installing cmake on Linux systems, required for the default raknet-native backend:
> 
> https://robots.uc3m.es/installation-guides/install-cmake.html
> 
> You can get it with your systems package manager. Alternatively per our docs you can use raknet-node backend (explained in docs) which should have prebuilds for Linux.

Only on root user?
