### ISSUE TITLE
jwt not active

### ISSUE THREAD

**Issue by hvlxh** [mhsjlw/pocket-minecraft-protocol#395]
```js
  minecraft-protocol New connection:  127.0.0.1/54828 +43s
  minecraft-protocol * new status 2 +0ms
  minecraft-protocol S -> request_network_settings {"client_protocol":582} +0ms
  minecraft-protocol S <- network_settings {
  compression_threshold: 512,
  compression_algorithm: 'deflate',
  client_throttle: false,
  client_throttle_threshold: 0,
  client_throttle_scalar: 0
} +1ms
  minecraft-protocol S -> login {"protocol_version":582,"tokens":{"identity":"{\"chain\":[\"eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFWFpuUG8xTWorTHF2WGtnUUFDY0gwd3RDTmlnMnRmQTlCYjlaWFMrR0oxVlNkbEEzL2Fh +107ms
  minecraft-protocol Verified client with mojang key ******************* +0ms
  minecraft-protocol undefined NotBeforeError: jwt not active
    at E:\Codes\Javascript\GreenFrogMCBE\node_modules\jsonwebtoken\verify.js:181:21
    at getSecret (E:\Codes\Javascript\GreenFrogMCBE\node_modules\jsonwebtoken\verify.js:97:14)
    at module.exports [as verify] (E:\Codes\Javascript\GreenFrogMCBE\node_modules\jsonwebtoken\verify.js:101:10)
    at verifyAuth (E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\handshake\loginVerify.js:26:27)
    at client.decodeLoginJWT (E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\handshake\loginVerify.js:54:27)       
    at Player.onLogin (E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\serverPlayer.js:82:46)
    at Player.readPacket (E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\serverPlayer.js:168:14)
    at Player.handle (E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\connection.js:172:16)
    at E:\Codes\Javascript\GreenFrogMCBE\node_modules\frog-protocol\src\server.js:93:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  date: 2023-05-04T07:01:59.000Z
} +27ms
  minecraft-protocol S <- disconnect {
  hide_disconnect_screen: false,
  message: 'Server authentication error'
} +10ms
  minecraft-protocol Kicked  127.0.0.1/54828 Server authentication error +201ms
  minecraft-protocol * new status 0 +313ms
  minecraft-protocol Connection closed:  127.0.0.1/54828 undefined +181ms
```

i tried deleting node_modules but still receiving

**Comment by extremeheat** [comment]
Why do you believe this is an issue with bedrock protocol? You need to provide more detailed information on this issue including steps to reproduce.

**Comment by hvlxh** [comment]
just created an server with offline: false and shows this

**Comment by hvlxh** [comment]
i'm able to connect to others server so not mc issue

**Comment by extremeheat** [comment]
Can't reproduce on 1.19.81, please provide more detailed steps to reproduce.

**Comment by extremeheat** [comment]
Delete your node_modules and package-lock.json then, do `npm install bedrock-protocol`, restart your game and try again. 

If you can reproduce this issue, reopen and provide the all example code you used to replicate this issue including the steps.

**Comment by hvlxh** [comment]
1. initialize an new project
2. install bedrock-protocol 
3. Use basicServer.js example code with debug on
4. Done

![image](https://user-images.githubusercontent.com/91016099/236435710-cf2ad4ed-c3be-487e-98ae-1da6311a7804.png)
![image](https://user-images.githubusercontent.com/91016099/236435726-3570b831-dadc-4619-a845-af2070946d23.png)

**Comment by LucienHH** [comment]
Can't seem to reproduce this either on latest release. 
![image](https://user-images.githubusercontent.com/66429271/236444609-c8d86b10-a99a-4a3c-9d0e-5abf92be87aa.png)

**Comment by hvlxh** [comment]
there's probably "an reason" for this issue tho

**Comment by hvlxh** [comment]
should i try reinstalling node-gyp?

**Comment by hvlxh** [comment]
i fixed the issue, it was due to the ntp was not synced. I will open an pr for this silly issues...

it took me 3 days for fix this issue

**Comment by extremeheat** [comment]
This could be added to the FAQ
