### ISSUE TITLE
Relay to hive: Server packet parse error on 1.20 client

### ISSUE THREAD

**Issue by GameParrot** [mhsjlw/pocket-minecraft-protocol#416]
How to reproduce:
1. Make a relay to the hive
2. Join from 1.20

Observed result:
"Server packet parse error"

This could be caused by an unsupported packet. Versions older than 1.20 do not have this problem. This may also occur on other servers.

**Comment by GameParrot** [comment]
![image](https://github.com/PrismarineJS/bedrock-protocol/assets/85067619/edf69f24-685a-4047-afd6-595f9025277d)
```
127.0.0.1/49320 Read failure for 0x8a <Buffer 8a 01 a9 08 24 35 39 64 39 65 37 38 63 2d 66 30 62 62 2d 34 66 31 34 2d 39 65 39 62 2d 37 61 62 34 66 35 38 66 66 62 66 35 00 00 02>
127.0.0.1/49320 PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/home/gameparrot/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/home/gameparrot/node_modules/protodef/src/utils.js:70:5)
    at Object.reader [as li32] (/home/gameparrot/node_modules/protodef/src/datatypes/numeric.js:89:48)
    at Object.DeviceOS (eval at compile (/home/gameparrot/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1675:41)
    at Object.packet_emote (eval at compile (/home/gameparrot/node_modules/protodef/src/compiler.js:258:12), <anonymous>:3717:73)
    at eval (eval at compile (/home/gameparrot/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1830:50)
    at mcpe_packet (eval at compile (/home/gameparrot/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1896:9)
    at CompiledProtodef.read (/home/gameparrot/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/home/gameparrot/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/home/gameparrot/node_modules/protodef/src/utils.js:50:16) {
  partialReadError: true
}
```

**Comment by MrDiamond64** [comment]
should be fixed with this pr: https://github.com/PrismarineJS/minecraft-data/pull/718

**Comment by GameParrot** [comment]
How do I update to it with npm?

**Comment by AnyBananaGAME** [comment]
`npm update --depth 9999`

**Comment by extremeheat** [comment]
It is not yet released (missing a release PR), you can open one in minecraft-data

**Comment by extremeheat** [comment]
minecraft-data update was released last week, update with `npm update --depth 9999`
