### ISSUE TITLE
Server authentication error with relay

### ISSUE THREAD

**Issue by Atomic69420** [mhsjlw/pocket-minecraft-protocol#494]
When using relays to join a realm or server(only tried with realms but seems to be a issue for both) and joining the relay will give a error saying Server authentication error on 1.20.71. the full error is below
Error: NotBeforeError: jwt not active
    at RelayPlayer.onLogin (C:\Users\USER-PC\Downloads\relayac\node_modules\bedrock-protocol\src\serverPlayer.js:87:13)
    at RelayPlayer.readPacket (C:\Users\USER-PC\Downloads\relayac\node_modules\bedrock-protocol\src\serverPlayer.js:169:14)
    at RelayPlayer.readPacket (C:\Users\USER-PC\Downloads\relayac\node_modules\bedrock-protocol\src\relay.js:156:13)
    at RelayPlayer.handle (C:\Users\USER-PC\Downloads\relayac\node_modules\bedrock-protocol\src\connection.js:170:16)
    at C:\Users\USER-PC\Downloads\relayac\node_modules\bedrock-protocol\src\server.js:105:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by Atomic69420** [comment]
also forgot to say but I am on 1.20.73 the relays on 1.20.71

**Comment by extremeheat** [comment]
You need to sign out and back in

**Comment by Atomic69420** [comment]
I tried that. With just minecraft and with a bedrock protocol client nothing seemed to change. I did once get to the relay kicking me asking me to login but after I did and tried to reconnect it prompted me with the same error

**Comment by Atomic69420** [comment]
I found out why it was doing that it was cause my computer was 1 minute off from the real time
