### ISSUE TITLE
ping example question

### ISSUE THREAD

**Issue by waternoob1005** [mhsjlw/pocket-minecraft-protocol#509]
```
RakTimeout [Error]: Ping timed out
    at C:\Users\1\Desktop\TSPL\node_modules\bedrock-protocol\src\rak.js:75:13
    at waitFor (C:\Users\1\Desktop\TSPL\node_modules\bedrock-protocol\src\datatypes\util.js:30:32)
    at async ping (C:\Users\1\Desktop\TSPL\node_modules\bedrock-protocol\src\createClient.js:89:41)

Node.js v21.7.1
```
when this error occurs, how can I just know that an error has occurred instead of ending with an error?

**Comment by extremeheat** [comment]
You catch the exception with the `error` event, then reconnect.
