### ISSUE TITLE
UNAUTHORIZED 

### ISSUE THREAD

**Issue by fancode343** [mhsjlw/pocket-minecraft-protocol#545]
This error occur when i sign in xbox

Connecting to GJR1.aternos.me:51286 §2G§6J§1R (GJR), version 1.21.44  (as 1.21.42)
Error: 401 Unauthorized {
  "path" : "/multiplayer/bedrock/authentication",
  "error" : "UNAUTHORIZED"
}
    at checkStatus (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/common/Util.js:10:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BedrockTokenManager.getAccessToken (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/TokenManagers/MinecraftBedrockTokenManager.js:55:34)
    at async retry.xbl.forceRefresh (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:195:23)
    at async retry (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftBedrockToken (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:192:14)
    at async Object.authenticate (/cloudide/workspace/Nodejs/node_modules/.pnpm/bedrock-protocol@3.41.0/node_modules/bedrock-protocol/src/client/auth.js:68:20)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 401 Unauthorized {
  "path" : "/multiplayer/bedrock/authentication",
  "error" : "UNAUTHORIZED"
}
    at checkStatus (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/common/Util.js:10:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BedrockTokenManager.getAccessToken (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/TokenManagers/MinecraftBedrockTokenManager.js:55:34)
    at async retry.xbl.forceRefresh (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:195:23)
    at async retry (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftBedrockToken (/cloudide/workspace/Nodejs/node_modules/.pnpm/prismarine-auth@2.5.0/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:192:14)
    at async Object.authenticate (/cloudide/workspace/Nodejs/node_modules/.pnpm/bedrock-protocol@3.41.0/node_modules/bedrock-protocol/src/client/auth.js:68:20)
Emitted 'error' event on Client instance at:
    at Object.authenticate (/cloudide/workspace/Nodejs/node_modules/.pnpm/bedrock-protocol@3.41.0/node_modules/bedrock-protocol/src/client/auth.js:91:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.2

**Comment by Slauh** [comment]
Check if the account is banned

**Comment by Slauh** [comment]
you might need to play on the account if you haven't already

**Comment by fancode343** [comment]
Thanks
